import { ShieldCheck, Zap, Download, Mail, Github, Globe } from "lucide-react";

const ABOUT_CARDS = [
  {
    icon: Zap,
    title: "Fast responses",
    text: "Quick mode keeps the model warm in memory and caps the output, so the first words appear almost immediately and the whole doc lands in seconds.",
  },
  {
    icon: ShieldCheck,
    title: "Private by design",
    text: "Documentation is generated by a local model running next to the app. Your code is not sent to a third-party AI API.",
  },
  {
    icon: Download,
    title: "Export anywhere",
    text: "Download any document as PDF or DOCX, ready for GitHub, Jira, Confluence or an internal wiki.",
  },
];

const CONTACT_CARDS = [
  {
    icon: Mail,
    title: "Email",
    label: "docgenindia@gmail.com",
    href: "mailto:docgenindia@gmail.com",
  },
  {
    icon: Github,
    title: "GitHub",
    label: "SanjayMarathi/DocGen",
    href: "https://github.com/SanjayMarathi/DocGen",
  },
  {
    icon: Globe,
    title: "Hugging Face",
    label: "docgen/DocGen",
    href: "https://huggingface.co/spaces/docgen/DocGen",
  },
];

export function About() {
  return (
    <div className="animate-rise mx-auto w-full max-w-4xl">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">About DocGen</h1>
      <p className="mt-3 max-w-2xl text-base leading-relaxed text-ink/75">
        DocGen is an AI documentation engine that turns source code, problems and topics into
        structured, professional documents.
      </p>
      <div className="mt-8 grid gap-4 md:grid-cols-3">
        {ABOUT_CARDS.map(({ icon: Icon, title, text }) => (
          <div key={title} className="glass rounded-2xl p-5">
            <span className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-accent-ink">
              <Icon size={20} />
            </span>
            <h2 className="mb-1.5 text-lg font-semibold">{title}</h2>
            <p className="text-sm leading-relaxed text-ink/70">{text}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

export function Contact() {
  return (
    <div className="animate-rise mx-auto w-full max-w-4xl">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Contact</h1>
      <p className="mt-3 max-w-2xl text-base leading-relaxed text-ink/75">
        Questions, bugs or ideas? Reach us through any of these.
      </p>
      <div className="mt-8 grid gap-4 md:grid-cols-3">
        {CONTACT_CARDS.map(({ icon: Icon, title, label, href }) => (
          <a
            key={title}
            href={href}
            target={href.startsWith("http") ? "_blank" : undefined}
            rel="noreferrer noopener"
            className="glass group flex flex-col items-center rounded-2xl p-6 text-center transition-transform hover:-translate-y-0.5"
          >
            <span className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-lg bg-accent text-accent-ink">
              <Icon size={22} />
            </span>
            <h2 className="mb-1 text-lg font-semibold">{title}</h2>
            <span className="break-all text-sm font-medium underline decoration-accent decoration-[3px] underline-offset-4">
              {label}
            </span>
          </a>
        ))}
      </div>
    </div>
  );
}
